CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    paid_by_user_id BIGINT NOT NULL,
    description VARCHAR(180) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_expenses_group
        FOREIGN KEY (group_id)
        REFERENCES groups (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_expenses_paid_by
        FOREIGN KEY (paid_by_user_id)
        REFERENCES users (id)
);

CREATE TABLE expense_splits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount_owed NUMERIC(19, 2) NOT NULL,
    settled BOOLEAN NOT NULL DEFAULT FALSE,
    settled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_expense_splits_expense
        FOREIGN KEY (expense_id)
        REFERENCES expenses (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_expense_splits_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT uk_expense_splits_expense_user UNIQUE (expense_id, user_id)
);

CREATE INDEX idx_expenses_group ON expenses (group_id);
CREATE INDEX idx_expenses_paid_by ON expenses (paid_by_user_id);
CREATE INDEX idx_expense_splits_expense ON expense_splits (expense_id);
CREATE INDEX idx_expense_splits_user ON expense_splits (user_id);
CREATE INDEX idx_expense_splits_group_settled ON expense_splits (settled, expense_id);
